sshhost = '192.168.1.125'
sshuser = 'rosa'
sshport = '228'
messagesdirectory = '/home/rosa'
recpgpdir = '/home/squidtree/recipientpub.asc'
usrpgpdir = '/home/squidtree/senderpriv.asc'
userpgppassword = 'C0nfusedSquid'
